name: mermaid
version: 0.9.1
description: Dart JS interop for Mermaid - The Javascript tool that makes use of a markdown based syntax to render customizable diagrams, charts and visualizations.

homepage: https://github.com/timmaffett/mermaid.dart
repository: https://github.com/timmaffett/mermaid.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.4
  markdown: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.10
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
  lints: ^1.0.1
  test: ^1.21.0
